name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command `...`
        2. See error `...`
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe the actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please include relevant logs from `~/.claude/hooks/dispatcher.log`
        Tip: You can attach files by clicking this area to highlight it and then dragging files in.
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      value: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04]
        - Go version: [e.g., 1.25.4]
        - Claude Hooks version: [e.g., v1.0.0 or commit hash]
        - Claude Code version: [e.g., 1.0.0]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or information that might be helpful
      placeholder: Add any other context about the problem here
